{
    "cannotsubmitquizdueto": "De test can niet ingestuurd worden om volgende redenen:",
    "confirmcontinueoffline": "Deze poging is niet meer gesynchroniseerd sinds {{$a}}. Als je verder gewerkt hebt aan deze poging met een ander toestel na dit moment, dan kun je data verliezen.",
    "confirmleavequizonerror": "Er is een fout opgetreden tijdens het bewaren van je antwoorden. Weet je zeker dat je de test wil verlaten?",
    "errorbehaviournotsupported": "Deze test kan niet gemaakt worden in de app omdat het gedrag ervan niet ondersteund wordt door de app:",
    "errordownloading": "Fout bij het downloaden van vereiste data",
    "errorgetattempt": "Fout bij het ophalen van de poginggegevens.",
    "errorgetquestions": "Fout bij het ophalen van de vragen",
    "errorgetquiz": "Fout bij het ophalen van de testgegevens.",
    "errorparsequestions": "Er is een fout opgetreden bij het lezen van de vragen. Probeer deze test in een browser.",
    "errorquestionsnotsupported": "Deze test kan niet gemaakt worden in de app omdat die vragen bevat die door de app niet ondersteund worden:",
    "errorrulesnotsupported": "Deze test kan niet gemaakt worden in de app omdat er toegangsregels in zitten die niet door de app ondersteund worden:",
    "errorsaveattempt": "Er is een fout opgetreden bij het bewaren van de gegevens van de poging.",
    "errorsyncquiz": "Er is een fout opgetreden tijdens de synchronisatie. Probeer opnieuw.",
    "errorsyncquizblocked": "Deze test kan nu niet gesynchroniseerd worden omdat er een bewerking nog bezig is. Probeer later opnieuw. Als het probleem blijft, herstart dan de app.",
    "finishnotsynced": "Klaar maar niet gesynchroniseerd",
    "hasdatatosync": "De test heeft offline data die gesynchroniseerd moet worden.",
    "opentoc": "Open navigatie.",
    "warningattemptfinished": "Offline poging is verwijderd omdat ze op de site voltooid was of niet gevonden.",
    "warningdatadiscarded": "Sommige offline antwoorden werden verwijderd omdat te vragen online gewijzigd werden.",
    "warningdatadiscardedfromfinished": "De poging is niet beÃ«indigd omdat de offline antwoorden geweigerd werden. Bekijk je antwoorden opnieuw en stuur de poging opnieuw in."
}